### ISSUE TITLE
Instant death in 8-Airship Bowser Jr. Battle

### ISSUE THREAD

**Issue by justdeiz** [NSMBW-Community/Reggie-Next#52] opened 2024-09-05 21:16 UTC
https://github.com/user-attachments/assets/0a067933-7ca6-4324-a531-6e4359476ea1

[config.json](https://github.com/user-attachments/files/16900296/config.json)

When you enter the 8-Airship bowser jr. battle, the camera is all messed up and you die instantly.
I have attached my config.json, the airship boss fight is in 3-5.

**Comment by CLF78** [comment] 2024-09-05 21:56
This is most likely caused by hardcoded behaviour specific to the 8-Airship boss battle. Not sure why you'd think it's Reggie Next's fault since all you're using is a level randomizer. Closing issue for being unrelated to Reggie Next.

**Closed by CLF78** 2024-09-05 21:56 UTC

**Comment by justdeiz** [comment] 2024-09-05 21:58
I'm so sorry I sent this to the wrong repo lmao
